# Generated by Django 3.2.5 on 2021-07-25 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_joined',
            field=models.CharField(default=datetime.date(2021, 7, 25), max_length=20),
        ),
    ]
