# Generated by Django 3.2.5 on 2021-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_joined',
            field=models.CharField(max_length=20),
        ),
    ]
