# Generated by Django 3.2.5 on 2021-07-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_joined',
            new_name='date_created',
        ),
    ]
