# Generated by Django 3.2.5 on 2021-07-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_rename_date_joined_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
